# Generated by Django 4.0.6 on 2022-07-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date',
            field=models.DateField(verbose_name='Game date'),
        ),
    ]
