# Generated by Django 4.0.6 on 2022-07-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_games_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='games',
            name='game',
            field=models.CharField(choices=[('A', 'Away'), ('H', 'Home')], default='A', max_length=1),
        ),
    ]
