# Generated by Django 4.0.6 on 2022-07-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_games_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='shoes',
            field=models.ManyToManyField(to='main_app.shoes'),
        ),
    ]
