# Generated by Django 4.0.6 on 2022-08-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_player_user_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
    ]
