# Generated by Django 4.0.6 on 2022-08-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_games_game_alter_game_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Shoe',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='shoes',
            new_name='shoe',
        ),
    ]
