# Generated by Django 4.0.6 on 2022-08-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_game_games_rename_shoe_shoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date',
            field=models.DateField(),
        ),
    ]
