# Generated by Django 4.0.6 on 2022-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_games_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='apg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rpg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='spg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ppg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.FloatField(),
        ),
    ]
