# Generated by Django 4.0.6 on 2022-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_shoes_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='college',
        ),
        migrations.AddField(
            model_name='player',
            name='per',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
