# Generated by Django 4.0.6 on 2022-09-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_player_college_player_height_player_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_Image',
            field=models.ImageField(null=True, upload_to='bball_draft_project/files/players'),
        ),
    ]
