# Generated by Django 4.0.6 on 2022-09-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_player_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
