# Generated by Django 4.0.6 on 2022-09-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_player_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_Image',
            field=models.ImageField(blank=True, null=True, upload_to='players/files/players'),
        ),
    ]
